variables:
  PLUGIN_NAME: 'carinianaPreservation'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs_plugins_unit_tests_model.yml'
      - 'templates/groups/ojs_plugins_cypress_tests_model.yml'

.unit_test_template:
  before_script:
    - apt update && apt install php{8.1,7.4,7.3}-gd php{8.1,7.4,7.3}-zip -yqq
    - composer install

.integration_tests:
  before_script:
    - composer install

release_plugin:
  before_script:
    - apt update && apt install php-gd php-zip php-xml php-mbstring -yqq
