variables:
  PLUGIN_NAME: 'carinianaPreservation'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs_plugins_unit_tests_model.yml'

unit_tests:
  before_script:
    - apt update && apt install php-gd php-zip -yqq
    - composer install

release_plugin:
  before_script:
    - apk add php-mbstring php-simplexml php-common php-fileinfo php-xml php-gd php-zip php-fpm php-xmlwriter php-xmlreader php-dom php-pdo php-opcache php-zip php-phar php-iconv php-cli --upgrade --no-cache
