variables:
  PLUGIN_NAME: 'carinianaPreservation'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs_plugins_unit_tests_model.yml'

unit_tests:
  before_script:
    - composer install