variables:
  PLUGIN_NAME: 'carinianaPreservation'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_5_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/unit_tests.yml'
      - 'templates/groups/ojs/cypress_tests.yml'

.php_dependencies: &php_dependencies
  before_script:
    - apt update && apt install php-gd php-zip php-xml php-mbstring -yqq

.unit_test_template:
  before_script:
    - apt update && apt install php-gd php-zip -yqq
    - composer install

.integration_tests_template:
  before_script:
    - apt update && apt install php-gd php-zip php-xml php-mbstring -yqq
    - composer install
    - sed -i '$a\[carinianapreservation]\nemail_for_tests = "teste@email.com"' /var/www/$CY_APPLICATION/config.inc.php

ojs_integration_tests:
  <<: *php_dependencies

code_formatting_check:
  <<: *php_dependencies

release_plugin:
  <<: *php_dependencies
